### ISSUE TITLE
Convert all FAQ pages to modals

### ISSUE THREAD

**Issue by karkar** [tractdb/tummy-trials#17]
I think we might need to convert all the FAQ pages to modals for making them globally accessible. 
Right now there are certain pages which are part of study_setup, which when accessed will change lead the page to be isolate (without a back button). This should be fixed if we consistently use modals whereby we reduce the need for back navigation.

**Comment by jayfo** [comment]
Without fully understanding the implications of "modal" here, it may also be that you have one FAQ which is good for browsing, then another which draws upon the same data in popups.

**Comment by jeffsco** [comment]
> Without fully understanding the implications of "modal" here, it may also be that you have one FAQ which is good for browsing, then another which draws upon the same data in popups.

For what it's worth, this is what I was thinking also.

J
