### ISSUE TITLE
Result page bug

### ISSUE THREAD

**Issue by karkar** [tractdb/tummy-trials#75]
Error prevents interacting with results visualization. Once a user interacts (changes viz views) in a result page, if the user navigates away from that page and tries to interact (change viz view) in another or the same page, the app throws the following error. 

`Error:` Attempted to assign to readonly property.

Error thrown on the update vis function in d3 controller. Seems like an iOS issue but need to check in detail. 

 `scope.control.updateVis = function(){`

**Comment by karkar** [comment]
Also, if you comment out 'use strict' on d3ctrl and pasttrial1ctrl the error changes to

`Error: undefined is not an object (evaluating 'scope.control')`

**Comment by jeffsco** [comment]
The message:

    Error: undefined is not an object (evaluating 'scope.control')

suggests that `scope` is undefined. For the code you cite (`scope.control.updateVis = ...`), this should not be possible.

On the other hand, I would have thought that the code you show would be executed when the page with the directive is formatted, not when the user interacts with the page.

Possibly the failing code is elsewhere?

**Comment by karkar** [comment]
It might be a nuance of the directive. The visualization is a part of the directive and is displaying properly, it's only when the functions to update the visualization are called that the error is thrown. Is there any scope propagation mechanic in play here?

**Comment by jeffsco** [comment]
Well, just at the level of language semantics, `scope` should exist as long as there is a reference to it. Nothing in the code assigns to `scope`, so it should always have the same value. It's defined earlier in the code (or you would get an error at the first occurrence of `scope.xxx`). It doesn't make sense that it would suddenly go undefined.

If there error were at this line:

        scope.visdata = Vis;

that would be more comprehensible (though still not comprehensible :-)

If the error really is later, it suggests wild behavior (violation of language semantics). Not a happy thought. Most likely something else is going on.

It's around 99.9% likely that you can find the error by adding tracing and working through the problem in a painstaking way. If you want me to look at it, I'm happy to. I need to know how to recreate the problem. Does it happen in the simulator (that seems easier to deal with)?

**Comment by karkar** [comment]
You can recreate it in the simulator (with safari console). 

Open a results page with the visualization click the buttons to switch between visualizations. 
Go back to my trials page
Open the same or different results page. You should see the error message. The buttons do not change between visualizaton now. 

See if you can find the problem without spending too much time. Else I'll take a stab at it over the weekend of something.
